### ISSUE TITLE
Edit filter lists

### ISSUE THREAD

**Issue by ErSpieltHD** [jojost1/adguardhomeremote-translations#10]
Hey there,
please make it possible to edit filter lists like the name or the URL.

**Comment by jojost1** [comment]
Hi, I'd love to add this, but sadly the Pi-hole API does not support this yet. When it supports it, I can build it!

**Comment by ErSpieltHD** [comment]
Uhm this is AdGuard

**Comment by jojost1** [comment]
Ah, I'm sorry my bad 😄 good suggestion, I'll see what I can do! For AdGuard Home I do think it's possible. Please send me feature suggestions using mail, this repo is really just for tracking translations! :-)
